services:
  nextjs:
    image: robertstarke/whiskyapp
    build:
      context: .
      dockerfile: nextjs_dockerfile
    ports:
      - 3000:3000
    depends_on:
      - strapi

  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: whiskyapp
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    ports:
      - 1337:1337
    volumes:
        - strapi_whiskyapp:/srv/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=whiskyapp
    volumes:
      - db_whiskyapp:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongo

volumes:
  db_whiskyapp:
    driver: local
  strapi_whiskyapp:
    driver: local
