apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  labels:
    app: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: robertstarke/whiskyapp
          imagePullPolicy: Always
          env:
            - name: CMS_URL_BACKEND
              value: http://localhost:1337/graphql
          ports:
            - containerPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: nextjs-secret
