apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: whiskyapp
spec:
  selector:
    app: strapi
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: LoadBalancer
